create schema lab1;
use lab1;
create table THEMEPARK(
	PARK_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    PARK_NAME VARCHAR(35) NOT NULL,
    PARK_CITY VARCHAR(50) NOT NULL,
    PARK_COUNTR_Y CHAR(2) NOT NULL

);

create table EMPLOYEE(
	EMP_NUM  NUMERIC(4) NOT NULL PRIMARY KEY,
    EMP_TITLE VARCHAR(4),
    EMP_LNAME VARCHAR(15) NOT NULL,
    EMP_FNAME VARCHAR(15) NOT NULL,
    EMP_DOB DATE NOT NULL,
    EMP_HIRE_DATE DATE NOT NULL,
    EMP_AREACODE VARCHAR(4) NOT NULL,
    EMP_PHONE VARCHAR (12) NOT NULL,
    PARK_CODE VARCHAR(10) NOT NULL,
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK(PARK_CODE)
);

create table TICKET(
	TICKET_NO NUMERIC(10) NOT NULL PRIMARY KEY,
    TICKET_PRICE NUMERIC(4,2),
    TICKET_TYPE VARCHAR(10) NOT NULL,
    PARK_CODE VARCHAR(10) NOT NULL,
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK(PARK_CODE)
);

create table ATTRACTION(
	ATTRACT_NO NUMERIC(10) NOT NULL PRIMARY KEY,
    PARK_CODE VARCHAR(10) NOT NULL,
    ATTRACT_NAME VARCHAR(35) NOT NULL,
    ATTRACT_AGE NUMERIC(3) DEFAULT 0,
    ATTRACT_CAP NUMERIC(3) NOT NULL,
    ATTRACT_CAP_ACITY NUMERIC(3),
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK(PARK_CODE)
    
);

create table HOUR (
	EMP_NUM NUMERIC(4) NOT NULL PRIMARY KEY,
    ATTRACT_NO NUMERIC(10) NOT NULL PRIMARY KEY,
    HOURS_PER_AT_TRACT NUMERIC(2) NOT NULL,
    HOUR_RATE NUMERIC(4,2) NOT NULL,
    DATE_WORKED DATE NOT NULL,
    FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE(EMP_NUM),
    FOREIGN KEY (ATTRACT_NO) REFERENCES ATTRACTION(ATTRACT_NO)
    
);

create table SALES (
	TRANSACTION_NO  NUMERIC NOT NULL PRIMARY KEY,
    PARK_CODE VARCHAR(10) NOT NULL,
    SALE_DATE DATE NOT NULL,
    FOREIGN KEY (PARK_CODE) REFERENCES THEMEPARK(PARK_CODE)
);

create table SALESLINE (
	TRANSACTION_NO NUMERIC NOT NULL PRIMARY KEY,
    LINE_NO NUMERIC(2) NOT NULL,
    TICKET_NO  NUMERIC(10) NOT NULL,
    FOREIGN KEY (TICKET_NO) REFERENCES TICKET(TICKET_NO),
    LINE_QTY NUMERIC (4) NOT NULL,
    LINE_PRICE  NUMERIC(9.2) NOT NULL,
    FOREIGN KEY (TRANSACTION_NO) REFERENCES SALES(TRANSACTION_NO)
);
